# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto

builds:
  - id: binary
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease
  - id: win_binary
    goos:
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease
  - id: msi
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease
    hooks:
      post: go-msi make --msi dist/jsonte-{{.Version}}.msi --version {{.Version}} --src .\templates --out .\go-msi-tmp

archives:
  - builds:
      - binary
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}x86
      {{- else }}{{ .Arch }}{{ end }}
      {{- if eq .Arch "arm" }}-{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
  - builds:
      - win_binary
    id: win_binary
    format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}x86
      {{- else }}{{ .Arch }}{{ end }}
      {{- if eq .Arch "arm" }}-{{ .Arm }}{{ end }}
    files:
      - src: scripts/jsonte-update.ps1
        dst: ./
        strip_parent: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Tag }}"

changelog:
  filters:
    exclude:
      # For excluding docs related commits
      - '^docs:'
      # For excluding configuration related commits
      - '^config:'
      # For excluding small typo commits
      - '^typo:'
      # For excluding dependencies related commits
      - '^dep:'
  sort: asc

release:
  extra_files:
    - glob: "./**/jsonte-*.msi"
