name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Sync vendor directory
        run: |
          go mod vendor
        shell: bash
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          repository: 'MCDevKit/regolith-library'
          token: ${{ secrets.GH_PAT }}
          path: './regolith-library'
      - name: Copy artifacts
        working-directory: './regolith-library'
        run: |
          cp ../dist/win_binary_windows_amd64/jsonte.exe ./jsonte/jsonte.exe
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./jsonte/jsonte.exe
          git commit -m "JSON Templating Engine v${{github.ref_name}}"
          git push origin main
          git tag jsonte-${{ github.ref_name }}
          git push --tags